#=~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
#   Project      : MAGEMin_C
#   License      : GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007
#   Developers   : Nicolas Riel, Boris Kaus
#   Contributors : Moccetti, N. B., Dominguez, H., Assunção J., Green E., Dolejš, D., Berlie N., and Rummel L.
#   Organization : Institute of Geosciences, Johannes-Gutenberg University, Mainz
#   Contact      : nriel[at]uni-mainz.de
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ =#
# This script generates the reference points of the nullspace optimizer test suite (optimizer=1, solver=0)
# One file test_diagram_ns_<case>.jl is written per case of ns_cases.jl; points that do not converge are skipped

cur_dir = pwd();    
if  cur_dir[end-3:end]=="test"
    cd("../")           # change to main directory if we are in /test
end
using MAGEMin_C

include(joinpath(@__DIR__, "ns_cases.jl"))

for c in ns_cases
    P, T    = ns_case_points(c)
    out     = ns_case_run(c, P, T)

    lines   = String[]
    for i in eachindex(out)
        if out[i].status != 0
            println("  skipped $(c.name) P=$(P[i]) T=$(T[i]) (status $(out[i].status))")
            continue
        end
        push!(lines, "outP{Float64}($(P[i]), $(T[i]), $(c.test), $(out[i].G_system), $(out[i].ph), $(out[i].ph_frac[:]))")
    end

    open(joinpath(@__DIR__, "test_diagram_ns_$(c.name).jl"), "w") do f
        println(f, "# Reference points of the nullspace optimizer test suite, case $(c.name) (db $(c.db)), generated by gen_tests_ns.jl")
        println(f, "list  = [", join(lines, ",\n"), "]")
    end
    println("$(c.name): $(length(lines))/$(length(P)) points")
end
