# Reference points of the nullspace optimizer test suite, case mtl_MF (db mtl), generated by gen_tests_ns.jl
list  = [outP{Float64}(150.0, 1400.0, -1, -495.3740901693913, ["fp"], [1.0]),
outP{Float64}(150.0, 1800.0, -1, -543.136487941805, ["fp"], [1.0]),
outP{Float64}(250.0, 1400.0, -1, -388.38311826543367, ["fp"], [1.0]),
outP{Float64}(250.0, 1800.0, -1, -434.79781929719616, ["fp"], [1.0])]
