#=~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
#   Project      : MAGEMin_C
#   License      : GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007
#   Developers   : Nicolas Riel, Boris Kaus
#   Contributors : Moccetti, N. B., Dominguez, H., Assunção J., Green E., Dolejš, D., Berlie N., and Rummel L.
#   Organization : Institute of Geosciences, Johannes-Gutenberg University, Mainz
#   Contact      : nriel[at]uni-mainz.de
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ =#
# Tests of the nullspace optimizer (optimizer=1, solver=0): reference diagrams generated by gen_tests_ns.jl,
# comparison with NLopt, reduced systems below FMAS, initial guesses and heat capacity

module NullspaceTests

using Test
using MAGEMin_C

include(joinpath(@__DIR__, "ns_cases.jl"))

mutable struct outP{ _T  }
    P           ::  _T
    T           ::  _T
    test        ::  Int64

    G           ::  _T
    ph          ::  Vector{String}
    ph_frac     ::  Vector{Float64}
end

absent_oxides(out, Xox)  = findall(o -> !(o in Xox), out.oxides)
absent_content(out, Xox) = maximum([maximum(abs.(ss.Comp[absent_oxides(out, Xox)])) for ss in out.SS_vec]; init = 0.0)

function verify_ns_point(out, ref, c :: ns_case)
    r1 = @test out.status == 0
    r2 = @test out.G_system ≈ ref.G atol=1e-3
    r3 = @test sort(out.ph) == sort(ref.ph)
    r4 = @test sort(out.ph_frac) ≈ sort(ref.ph_frac) atol=5e-3
    r5 = @test out.bulk_res_norm < 1e-8
    if c.test < 0
        @test all(out.bulk[absent_oxides(out, c.Xoxides)] .== 0.0)
        @test absent_content(out, c.Xoxides) < 1e-12
    end
    if any(r -> isa(r, Test.Fail), (r1, r2, r3, r4, r5))
        println("ERROR for case $(c.name); P=$(ref.P); T=$(ref.T); reference phases=$(ref.ph), G=$(ref.G); computed phases=$(out.ph), G=$(out.G_system)")
    end
    return nothing
end

@testset verbose=true "reference diagrams" begin
    for c in ns_cases
        @testset "$(c.name)" begin
            include(joinpath(@__DIR__, "test_diagram_ns_$(c.name).jl"))
            P   = [l.P for l in list]
            T   = [l.T for l in list]
            out = ns_case_run(c, P, T)
            for i in eachindex(list)
                verify_ns_point(out[i], list[i], c)
            end
        end
    end
end

@testset verbose=true "nullspace vs NLopt, full systems" begin
    for c in filter(c -> c.test >= 0, ns_cases)
        P, T = ns_case_points(c)
        o1   = ns_case_run(c, P, T)
        data = Initialize_MAGEMin(c.db, verbose=-1, solver=0, optimizer=0)
        o0   = multi_point_minimization(P, T, data, test=c.test, progressbar=false)
        Finalize_MAGEMin(data)
        for i in eachindex(P)
            @test o1[i].G_system < o0[i].G_system + 1e-4
            @test abs(o1[i].G_system - o0[i].G_system) < 1e-3
        end
    end
end

@testset verbose=true "SB databases, absent optional oxides" begin
    for (db, Xox, X) in [("sb11", ["SiO2", "Al2O3", "CaO", "MgO", "FeO"], [45.0, 8.0, 10.0, 35.0, 8.0]),
                         ("sb24", ["SiO2", "Al2O3", "CaO", "MgO", "Fe", "O"], [38.0, 2.8, 2.0, 50.0, 6.0, 0.1])]
        res = []
        for optimizer in (0, 1)
            data = Initialize_MAGEMin(db, verbose=-1, solver=0, optimizer=optimizer)
            push!(res, single_point_minimization(100.0, 1600.0, data, X=X, Xoxides=Xox, sys_in="mol"))
            Finalize_MAGEMin(data)
        end
        @test res[1].status == 0 && res[2].status == 0
        @test sort(res[2].ph) == sort(res[1].ph)
        @test abs(res[2].G_system - res[1].G_system) < 1e-4
        @test all(abs(sum(ss.emFrac) - 1.0) < 1e-8 for ss in res[2].SS_vec)
        @test absent_content(res[2], Xox) < 1e-12
    end
end

@testset verbose=true "nullspace solution-phase minimizer" begin
    for (db, test, P, T) in [("ig", 0, 8.0, 1100.0), ("ig", 2, 5.0, 900.0), ("mp", 0, 6.0, 650.0), ("mb", 0, 8.0, 800.0), ("um", 0, 10.0, 600.0), ("mtl", 0, 150.0, 1600.0)]
        res = []
        for optimizer in (0, 1)
            data = Initialize_MAGEMin(db, verbose=-1, solver=0, optimizer=optimizer)
            data = use_predefined_bulk_rock(data, test)
            push!(res, point_wise_minimization(P, T, data))
            Finalize_MAGEMin(data)
        end
        @test sort(res[2].ph) == sort(res[1].ph)
        @test res[2].G_system < res[1].G_system + 1e-5
        @test abs(res[2].G_system - res[1].G_system) < 1e-3
    end

    Xoxides = ["SiO2", "Al2O3", "CaO", "MgO", "FeO", "K2O", "Na2O", "H2O"]
    X       = [48.43, 15.19, 11.57, 10.13, 6.65, 0.42, 1.0, 3.0]
    res     = []
    for optimizer in (0, 1)
        data = Initialize_MAGEMin("ig", verbose=-1, solver=0, optimizer=optimizer)
        push!(res, single_point_minimization(5.0, 1000.0, data, X=X, Xoxides=Xoxides, sys_in="mol"))
        Finalize_MAGEMin(data)
    end
    @test sort(res[2].ph) == sort(res[1].ph)
    @test res[2].G_system < res[1].G_system + 1e-5

    @test_throws ErrorException Initialize_MAGEMin("ig", verbose=-1, optimizer=2)
end

@testset verbose=true "nullspace minimizer: reduced systems below FMAS" begin

    for (db, Xox, X, P, T, ph) in [ ("ig",  ["SiO2", "MgO"],                  [45.0, 35.0],             10.0,  1200.0, ["opx", "q"]),
                                    ("ig",  ["SiO2", "Al2O3", "MgO"],         [45.0, 10.0, 35.0],       10.0,  1200.0, ["opx", "q", "sill"]),
                                    ("ig",  ["SiO2", "Al2O3", "CaO", "MgO"],  [45.0, 10.0, 8.0, 35.0],  10.0,  1200.0, ["cpx", "fsp", "opx", "spl"]),
                                    ("mp",  ["SiO2", "Al2O3", "FeO", "H2O"],  [60.0, 20.0, 10.0, 5.0],  6.0,   650.0,  ["H2O", "g", "q", "st"]),
                                    ("um",  ["SiO2", "MgO", "H2O"],           [40.0, 50.0, 10.0],       10.0,  600.0,  ["atg", "ol", "ta"]),
                                    ("ume", ["SiO2", "CaO", "MgO"],           [45.0, 8.0, 35.0],        10.0,  600.0,  ["aug", "opx", "q"]),
                                    ("mtl", ["MgO", "FeO"],                   [35.0, 8.0],              150.0, 1600.0, ["fp"]) ]
        data = Initialize_MAGEMin(db, verbose=-1, solver=0, optimizer=1)
        out  = single_point_minimization(P, T, data, X=X, Xoxides=Xox, sys_in="mol")
        Finalize_MAGEMin(data)
        @test out.status == 0
        @test sort(out.ph) == sort(ph)
        @test all(out.bulk[findall(o -> !(o in Xox), out.oxides)] .== 0.0)
        @test absent_content(out, Xox) < 1e-12
        @test out.bulk_res_norm < 1e-10
    end

    Xox  = ["SiO2", "Al2O3", "CaO", "MgO"]
    X    = [45.0, 10.0, 8.0, 35.0]
    data = Initialize_MAGEMin("ig", verbose=-1, solver=0, optimizer=1)
    out1 = single_point_minimization(10.0, 1200.0, data, X=X, Xoxides=Xox, sys_in="mol")
    out2 = single_point_minimization(10.0, 1210.0, data, X=X, Xoxides=Xox, sys_in="mol")
    out3 = single_point_minimization(10.0, 1210.0, data, X=X, Xoxides=Xox, sys_in="mol", iguess=true, G=[out1.mSS_vec])
    @test sort(out3.ph) == sort(out2.ph)
    @test abs(out3.G_system - out2.G_system) < 1e-5
    @test absent_content(out3, Xox) < 1e-12

    full = Initialize_MAGEMin("ig", verbose=-1, solver=0, optimizer=1)
    full = use_predefined_bulk_rock(full, 0)
    outf = point_wise_minimization(10.0, 1200.0, full)
    Finalize_MAGEMin(full)
    out4 = single_point_minimization(10.0, 1210.0, data, X=X, Xoxides=Xox, sys_in="mol", iguess=true, G=[outf.mSS_vec])
    @test sort(out4.ph) == sort(out2.ph)
    @test abs(out4.G_system - out2.G_system) < 1e-5
    @test absent_content(out4, Xox) < 1e-12

    oxi_klb = ["SiO2", "Al2O3", "CaO", "MgO", "FeO", "K2O", "Na2O", "TiO2", "O", "Cr2O3", "H2O"]
    X_klb   = [38.494, 1.776, 2.824, 50.566, 0.0, 0.01, 0.25, 0.10, 0.096, 0.109, 0.0]
    for optimizer in (0, 1)
        d_klb = Initialize_MAGEMin("ig", verbose=-1, solver=0, optimizer=optimizer)
        o_klb = single_point_minimization(10.0, 1200.0, d_klb, X=X_klb, Xoxides=oxi_klb, sys_in="mol")
        Finalize_MAGEMin(d_klb)
        @test o_klb.status == 0
        @test o_klb.bulk[findfirst(==("O"), o_klb.oxides)] == 0.0
        @test (optimizer == 1) == (o_klb.bulk[findfirst(==("FeO"), o_klb.oxides)] == 0.0)
        @test o_klb.bulk_res_norm < 1e-8
    end

    X_klb0  = [38.494, 1.776, 2.824, 50.566, 0.0, 0.01, 0.25, 0.10, 0.0, 0.109, 0.0]
    d_klb   = Initialize_MAGEMin("ig", verbose=-1, solver=0, optimizer=1)
    corners = [single_point_minimization(P, T, d_klb, X=X_klb0, Xoxides=oxi_klb, sys_in="mol", name_solvus=true) for (P, T) in ((18.0, 1725.0), (24.0, 1725.0), (18.0, 1800.0), (24.0, 1800.0))]
    o_cold  = single_point_minimization(21.1038, 1787.5, d_klb, X=X_klb0, Xoxides=oxi_klb, sys_in="mol", name_solvus=true)
    o_warm  = single_point_minimization(21.1038, 1787.5, d_klb, X=X_klb0, Xoxides=oxi_klb, sys_in="mol", name_solvus=true, iguess=true, G=[vcat([c.mSS_vec for c in corners]...)])
    Finalize_MAGEMin(d_klb)
    @test o_warm.status == 0
    @test abs(o_warm.G_system - o_cold.G_system) < 1e-5
    @test sort(o_warm.ph) == sort(o_cold.ph)

    out5 = single_point_minimization(10.0, 1200.0, data, X=X, Xoxides=Xox, sys_in="mol", scp=1)
    @test out5.status == 0
    @test isfinite(out5.s_cp[1]) && out5.s_cp[1] > 0.0
    Finalize_MAGEMin(data)
end

end
